# Generated by Django 4.1.9 on 2023-05-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaillinkchecker', '0006_sitepreferences_email_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlink',
            name='follow',
            field=models.BooleanField(default=False),
        ),
    ]
