# Generated by Django 4.1.9 on 2023-05-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaillinkchecker', '0007_scanlink_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='run_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scan',
            name='verbosity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
