# Generated by Django 4.1.9 on 2023-05-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaillinkchecker', '0008_scan_run_sync_scan_verbosity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='automated_cleanup',
            field=models.BooleanField(default=False, help_text='Automatically remove old scans', verbose_name='Automated Cleanup'),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='automated_cleanup_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Number of days to keep scans in automated cleanup', verbose_name='Automated Cleanup Age'),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='email_reports',
            field=models.BooleanField(default=False, help_text='Send report emails after automated scans', verbose_name='Email Reports'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='automated_scanning',
            field=models.BooleanField(default=False, help_text='Conduct automated sitewide scans for broken links', verbose_name='Automated Scanning'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='email_recipient',
            field=models.EmailField(blank=True, default='', help_text='Recipient of the full problem report emails (page owners get reports too)', max_length=254, verbose_name='Email Recipient'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='email_sender',
            field=models.EmailField(blank=True, default='', help_text='Sender of the problem report emails', max_length=254, verbose_name='Email Sender'),
        ),
    ]
