# Generated by Django 4.1.9 on 2023-05-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaillinkchecker', '0009_sitepreferences_automated_cleanup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlink',
            name='domainname',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
