# Generated by Django 4.1.9 on 2023-05-11 15:43

from urllib.parse import urlparse
from django.db import migrations


def add_domainname(apps, schema_editor):
    ScanLink = apps.get_model('wagtaillinkchecker', 'ScanLink')
    for link in ScanLink.objects.all():
        parsed = urlparse(link.url)
        link.domainname = parsed.netloc
        link.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaillinkchecker', '0010_scanlink_domainname'),
    ]

    operations = [
        migrations.RunPython(add_domainname, migrations.RunPython.noop),
    ]
