# Generated by Django 4.1.9 on 2023-05-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaillinkchecker', '0011_auto_20230511_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='user_agent',
            field=models.CharField(blank=True, default='', help_text='User-Agent header to use in scans', max_length=500, verbose_name='User-Agent Header'),
        ),
    ]
