# Generated by Django 4.1.12 on 2023-10-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaillinkchecker', '0012_sitepreferences_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='html_validate',
            field=models.BooleanField(default=False, help_text='Use validator.w3.org to check pages', verbose_name='Use HTML validator'),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='html_validator_url',
            field=models.URLField(blank=True, default='https://validator.w3.org/nu/?out=json', help_text='URL of validator to check pages', verbose_name='HTML validator URL'),
        ),
    ]
